language: cpp
matrix:
  include:
    - compiler: gcc
      os: linux
      sudo: required
      dist: focal
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      before_install:
        - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
        - sudo apt-get update -qq
        - sudo apt-get install -y software-properties-common
        - sudo apt-get install -qq build-essential curl g++ libboost1.67-dev
    - compiler: clang
      os: osx
      env: CXX=clang++
      env: CC=clang
      env: LINK=clang++
script:
  - g++ -std=c++14 -c -pipe -g -Wall -W -fPIC  -I. -o main.o main.cpp
  - g++ -std=c++14 -c -pipe -g -Wall -W -fPIC  -I. -o interface.o interface.cpp
  - g++ -std=c++14 -o tool main.o interface.o  
  - ./tool
